//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StokAppDbEntities : DbContext
    {
        public StokAppDbEntities()
            : base("name=StokAppDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Depo> Depo { get; set; }
        public virtual DbSet<Grup> Grup { get; set; }
        public virtual DbSet<Malzeme> Malzeme { get; set; }
        public virtual DbSet<OlcuBirim> OlcuBirim { get; set; }
        public virtual DbSet<StokCikis> StokCikis { get; set; }
        public virtual DbSet<StokGiris> StokGiris { get; set; }
    }
}
